#!/bin/bash

HOME=/usr/share/cma

NAME=$(cat $HOME/name 2>/dev/null)
[ -z "$NAME" ] && NAME="rest"

$HOME/sched
$HOME/notify $NAME updated

$HOME/notify $NAME restarting
$HOME/stop
sleep 300
$HOME/start
 