#!/bin/bash

HOME=/usr/share/cma

$HOME/sched
$HOME/notify updated

[ $(cat $HOME/name) = tm01 ] && echo "TM1" > $HOME/name
[ $(cat $HOME/name) = zdmy ] && echo "ZDM" > $HOME/name
[ $(cat $HOME/name) = ozas ] && echo "OZA" > $HOME/name
[ $(cat $HOME/name) = ahum ] && echo "AHU" > $HOME/name
[ $(cat $HOME/name) = mstu ] && echo "MST" > $HOME/name
